TIME:     18:09:2023   16:02:19
TYPE:     Method error
REQUEST:     GET /setFound?id=71468443 HTTP/1.1
EXCEPTION:     1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRUE WHERE longid == 71468443' at line 1
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 80, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 15, in setFound
    cursor.execute("UPDATE ducks SET found TRUE WHERE longid == %s" % (id))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\opentelemetry\context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 1069, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 846, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRUE WHERE longid == 71468443' at line 1



TIME:     18:09:2023   16:03:07
TYPE:     Method error
REQUEST:     GET /setFound?id=71468443 HTTP/1.1
EXCEPTION:     1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRUE WHERE longid == 71468443' at line 1
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 80, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 15, in setFound
    print("here")
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\opentelemetry\context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 1069, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 846, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRUE WHERE longid == 71468443' at line 1



TIME:     18:09:2023   16:03:17
TYPE:     Method error
REQUEST:     GET /setFound?id=71468443 HTTP/1.1
EXCEPTION:     1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRUE WHERE longid == 71468443' at line 1
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 80, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 16, in setFound
    cursor.execute("UPDATE ducks SET found TRUE WHERE longid == %s" % (id))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\opentelemetry\context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 1069, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 846, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRUE WHERE longid == 71468443' at line 1



TIME:     18:09:2023   16:04:48
TYPE:     Method error
REQUEST:     GET /setFound?id=71468443 HTTP/1.1
EXCEPTION:     1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== 71468443' at line 1
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 80, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 16, in setFound
    cursor.execute("UPDATE ducks SET found = TRUE WHERE longid == %s" % (id))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\opentelemetry\context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 1069, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 846, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== 71468443' at line 1



TIME:     18:09:2023   16:07:30
TYPE:     Method error
REQUEST:     GET /setFound?id=71468443 HTTP/1.1
EXCEPTION:     1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== 71468443' at line 1
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 80, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 16, in setFound
    cursor.execute("UPDATE ducks SET found = TRUE WHERE longid == %s;" % (id))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\opentelemetry\context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 1069, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 846, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== 71468443' at line 1



TIME:     18:09:2023   16:07:36
TYPE:     Method error
REQUEST:     GET /setFound?id=71468443 HTTP/1.1
EXCEPTION:     1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== 71468443' at line 1
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 80, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 16, in setFound
    cursor.execute("UPDATE ducks SET found = TRUE WHERE longid == %s;" % (id))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\opentelemetry\context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 1069, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 846, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== 71468443' at line 1



TIME:     18:09:2023   16:07:46
TYPE:     Method error
REQUEST:     GET /setFound?id=71468443 HTTP/1.1
EXCEPTION:     1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== 71468443' at line 1
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 80, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 16, in setFound
    cursor.execute("UPDATE ducks SET found = TRUE WHERE longid == %s;" % (id))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\opentelemetry\context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 1069, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 846, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== 71468443' at line 1



TIME:     18:09:2023   16:08:13
TYPE:     Method error
REQUEST:     GET /setFound?id=71468443 HTTP/1.1
EXCEPTION:     1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== 71468443' at line 1
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 80, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 16, in setFound
    cursor.execute("UPDATE ducks SET found = TRUE WHERE longid == '%s';" % (id))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\opentelemetry\context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 1069, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 846, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== 71468443' at line 1



TIME:     18:09:2023   16:08:23
TYPE:     Method error
REQUEST:     GET /setFound?id=71468443 HTTP/1.1
EXCEPTION:     1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== 71468443' at line 1
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 80, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 16, in setFound
    cursor.execute("UPDATE ducks SET found = TRUE WHERE longid == '%s';" % (id))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\opentelemetry\context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 1069, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 846, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== 71468443' at line 1



TIME:     18:09:2023   16:08:29
TYPE:     Method error
REQUEST:     GET /setFound?id=71468443 HTTP/1.1
EXCEPTION:     1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== '71468443'' at line 1
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 80, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 16, in setFound
    cursor.execute("UPDATE ducks SET found = TRUE WHERE longid == '%s';" % (id))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\cursor.py", line 617, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\opentelemetry\context_propagation.py", line 77, in wrapper
    return method(cnx, *args, **kwargs)
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 1069, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\SebSm\AppData\Roaming\Python\Python310\site-packages\mysql\connector\connection.py", line 846, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== '71468443'' at line 1



TIME:     25:09:2023   16:20:20
TYPE:     Method error
REQUEST:     GET /getDucks HTTP/1.1
EXCEPTION:     can only concatenate str (not "tuple") to str
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 80, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 23, in getDucks
    data += x
TypeError: can only concatenate str (not "tuple") to str



TIME:     25:09:2023   16:20:58
TYPE:     Method error
REQUEST:     GET /getDucks HTTP/1.1
EXCEPTION:     can only concatenate str (not "tuple") to str
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 80, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 23, in getDucks
    print(data)
TypeError: can only concatenate str (not "tuple") to str



TIME:     25:09:2023   16:21:08
TYPE:     Method error
REQUEST:     GET /getDucks HTTP/1.1
EXCEPTION:     can only concatenate str (not "tuple") to str
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 80, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 23, in getDucks
    print(data)
TypeError: can only concatenate str (not "tuple") to str



TIME:     25:09:2023   16:22:26
TYPE:     Method error
REQUEST:     GET /getDucks HTTP/1.1
EXCEPTION:     can only concatenate str (not "int") to str
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 80, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 24, in getDucks
    data += x[0]
TypeError: can only concatenate str (not "int") to str



TIME:     25:09:2023   16:23:23
TYPE:     Method error
REQUEST:     GET /getDucks HTTP/1.1
EXCEPTION:     can only concatenate str (not "int") to str
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 80, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 24, in getDucks
    data += str(x[0])
TypeError: can only concatenate str (not "int") to str



TIME:     02:10:2023   12:04:55
TYPE:     Connection
REQUEST:     
EXCEPTION:     timed out
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 26, in start
    connSocket,sourceAddr = servSocket.accept()
  File "C:\Python310\lib\socket.py", line 293, in accept
    fd, addr = self._accept()
TimeoutError: timed out



TIME:     02:10:2023   12:05:13
TYPE:     Connection
REQUEST:     
EXCEPTION:     timed out
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 26, in start
    connSocket,sourceAddr = servSocket.accept()
  File "C:\Python310\lib\socket.py", line 293, in accept
    fd, addr = self._accept()
TimeoutError: timed out



TIME:     02:10:2023   12:26:04
TYPE:     Connection
REQUEST:     
EXCEPTION:     timed out
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 26, in start
    connSocket,sourceAddr = servSocket.accept()
  File "C:\Python310\lib\socket.py", line 293, in accept
    fd, addr = self._accept()
TimeoutError: timed out



TIME:     15:10:2023   22:19:17
TYPE:     Method error
REQUEST:     GET /getDucks HTTP/1.1
EXCEPTION:     SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 7108 and this is thread id 19652.
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 120, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 14, in getDucks
    cursor.execute("SELECT found FROM ducks")
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 7108 and this is thread id 19652.



TIME:     15:10:2023   22:19:51
TYPE:     Method error
REQUEST:     GET /getDucks HTTP/1.1
EXCEPTION:     SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 11632 and this is thread id 17312.
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 121, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 14, in getDucks
    cursor.execute("SELECT found FROM ducks")
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 11632 and this is thread id 17312.



TIME:     15:10:2023   22:26:54
TYPE:     Method error
REQUEST:     GET /getDucks HTTP/1.1
EXCEPTION:     SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 868 and this is thread id 10140.
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 121, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 14, in getDucks
    cursor.execute("SELECT found FROM ducks")
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 868 and this is thread id 10140.



TIME:     15:10:2023   22:27:20
TYPE:     Method error
REQUEST:     GET /getDucks HTTP/1.1
EXCEPTION:     SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 992 and this is thread id 5252.
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 121, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 14, in getDucks
    cursor.execute("SELECT found FROM ducks")
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 992 and this is thread id 5252.



TIME:     15:10:2023   22:27:53
TYPE:     Method error
REQUEST:     GET /getDucks HTTP/1.1
EXCEPTION:     SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 18264 and this is thread id 9468.
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 121, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 14, in getDucks
    cursor.execute("SELECT found FROM ducks")
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 18264 and this is thread id 9468.



TIME:     15:10:2023   22:28:22
TYPE:     Method error
REQUEST:     GET /getDucks HTTP/1.1
EXCEPTION:     SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 12876 and this is thread id 17764.
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 122, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 14, in getDucks
    cursor.execute("SELECT found FROM ducks")
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 12876 and this is thread id 17764.



TIME:     15:10:2023   22:29:55
TYPE:     Method error
REQUEST:     GET /getDucks HTTP/1.1
EXCEPTION:     SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 9428 and this is thread id 3160.
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 122, in handleRequest
    result = str(self.methods[methodName][0](**paramsDict))
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 14, in getDucks
    cursor.execute("SELECT found FROM ducks")
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 9428 and this is thread id 3160.



TIME:     15:10:2023   22:31:33
TYPE:     Method error
REQUEST:     GET /getDucks HTTP/1.1
EXCEPTION:     SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 9428 and this is thread id 16000.
TRACEBACK:     Traceback (most recent call last):
  File "C:\Users\SebSm\projects\ProjectDUCK\webServer.py", line 122, in handleRequest
    servResponse = 'HTTP1/0 404 NOT FOUND\n' + headerString +  'File Not Found'
  File "C:\Users\SebSm\projects\ProjectDUCK\server.py", line 14, in getDucks
    cursor.execute("SELECT found FROM ducks")
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 9428 and this is thread id 16000.



